model_list:
  - model_name: model1
    llm_params:
      api_type: openai # openai, anthropic
      model: gpt-3.5-turbo
      api_base: https://ega3235api.opefea6546eghawnai.com/v1
      api_key: sk-1234
  - model_name: model2
    llm_params:
      api_type: openai # openai, anthropic
      model: gpt-4
      api_base: https://aaegagegpi.opefeaf3462ewnai.com/v1
      api_key: sk-5678
  - model_name: model3
    llm_params:
      api_type: anthropic # openai, anthropic
      model: claude-3-opus
      api_base: https://apigaef.aeawfewnt42hfraweopicd.com/v1
      api_key: sk-9012
      
router_settings:
  strategy: roundrobin
  model_groups:
    - name: gpt_models
      models:
        - name: model1 # default weight 100
        - name: model2
          weight: 100
    - name: gpt_models2
      models:
        - name: model1


